INCLUDE_DIR   = /Users/include/poker

F90_FLAGS = -O3 -DGFORTRAN -fno-second-underscore -fopenmp
HEALPIX   = /Library/Healpix_2.20a
F90_LDFLAGS = -L$(F90_LIBDIR) -L$(FITSDIR) -lhealpix -lgif -l$(LIBFITS) -L/usr/local/lib/x86_64 -lfftw3


F90_INCDIR = $(HEALPIX)/include
F90_LIBDIR = $(HEALPIX)/lib

LIBFITS	  = cfitsio

F90_FC	    = gfortran
F90_FFLAGS  = -I$(F90_INCDIR) -I$(INCLUDE_DIR) -I$(INCLUDE_DIR) $(F90_FLAGS) -I/usr/local/include
F90_LDFLAGS = -L$(F90_LIBDIR) -L$(FITSDIR) -lhealpix -lgif -l$(LIBFITS) -L/usr/local/lib/x86_64 -lfftw3

OBJS = $(INCLUDE_DIR)/poker_types.o $(INCLUDE_DIR)/poker_input.o $(INCLUDE_DIR)/poker_tools.o

default: $(OBJS) $(NP_BIN)/poker_mbb $(NP_BIN)/poker_count_tasks $(NP_BIN)/poker_give_map_b

$(INCLUDE_DIR)/poker_types.o: poker_types.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_types.F90 
	mv poker_types.o poker_types.mod $(INCLUDE_DIR)

$(INCLUDE_DIR)/poker_tools.o: $(INCLUDE_DIR)/poker_types.o poker_tools.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_tools.F90 
	mv poker_tools.o poker_tools.mod $(INCLUDE_DIR)

$(INCLUDE_DIR)/poker_input.o: $(INCLUDE_DIR)/poker_types.o poker_input.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_input.F90 
	mv poker_input.o poker_input.mod $(INCLUDE_DIR)

$(NP_BIN)/poker_mbb: $(OBJS) poker_mbb.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_mbb.F90 
	$(F90_FC) $(F90_FFLAGS) $(HPX) $(OBJS) poker_mbb.o -o $(NP_BIN)/poker_mbb $(F90_LDFLAGS)
	rm -f poker_mbb.o

$(NP_BIN)/poker_give_map_b: $(OBJS) poker_give_map_b.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_give_map_b.F90 
	$(F90_FC) $(F90_FFLAGS) $(HPX) $(OBJS) poker_give_map_b.o -o $(NP_BIN)/poker_give_map_b $(F90_LDFLAGS)
	rm -f poker_give_map_b.o

$(NP_BIN)/poker_count_tasks: $(OBJS) poker_count_tasks.F90
	$(F90_FC) $(F90_FFLAGS) -c poker_count_tasks.F90 
	$(F90_FC) $(F90_FFLAGS) $(HPX) $(OBJS) poker_count_tasks.o -o $(NP_BIN)/poker_count_tasks $(F90_LDFLAGS)
	rm -f poker_count_tasks.o

clean:
	rm -f $(INCLUDE_DIR)/*mod $(INCLUDE_DIR)/*.o $(NP_BIN)/poker $(NP_BIN)/poker_count_tasks $(NP_BIN)/check_fits_sub
