! Copyright 2010, Nicolas Ponthieu, Julien Grain, Guilaine Lagache
! 
! This file is part of Poker.
! 
! Poker is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
! 
! Poker is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
! 
! You should have received a copy of the GNU General Public License
! along with Poker.  If not, see <http://www.gnu.org/licenses/>.
! 
! For more information about Poker, see http://www.ias.u-psud.fr/poker
! ======================================================================


! Automatically generated by make_read_params_f90.pl
! Extracted from template.dat
! 111022_23:33:52

module poker_types
use healpix_types
implicit none

public :: poker_str

type poker_str
CHARACTER(LEN=200) :: map
CHARACTER(LEN=200) :: map_k_binning
REAL(DP) :: res_pix
CHARACTER(LEN=200) :: report_card
CHARACTER(LEN=200) :: mask
INTEGER(I4B) :: nbeams
CHARACTER(LEN=200) :: beam
CHARACTER(LEN=200) :: beam1
CHARACTER(LEN=200) :: file_map_b
CHARACTER(LEN=200) :: file_mtt_bb
CHARACTER(LEN=200) :: file_mtt_bb_1
CHARACTER(LEN=200) :: file_mtt_bb_x
INTEGER(I4B) :: simul_type
CHARACTER(LEN=200) :: input_bintab
INTEGER(I4B) :: include_pix_window_function
INTEGER(I4B) :: verb
INTEGER(I4B) :: n_cpu_max
REAL(DP) :: scale
REAL(DP) :: delta_l_over_l
REAL(DP) :: beta
INTEGER(I4B) :: log_binning
CHARACTER(LEN=200) :: dir
CHARACTER(LEN=200) :: outparfile
INTEGER(I4B) :: nx
INTEGER(I4B) :: ny
INTEGER(I4B) :: nx_large
INTEGER(I4B) :: ny_large
CHARACTER(LEN=200) :: patch
INTEGER(I4B) :: remove_1st_bin
CHARACTER(LEN=200) :: k_out
INTEGER(I4B) :: keep_avg
REAL(DP) :: k_nyquist
INTEGER(I4B) :: apod_length
REAL(DP) :: dk_min
end type poker_str 


end module poker_types
